name: CI
on:
  push:
    branches:
      - main
      - develop
      - release/*
  pull_request:
    branches:
      - main
      - develop
      - release/*

jobs:
  quality:
    name:  SonarQube Quality Gate
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: '6.0'
          mongodb-port: 27017
          mongodb-replica-set: rs0
      
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v2.x
          
      - name: Test
        run: deno test -A --coverage=cov_profile
        working-directory: library